[package]
name = "sp-arithmetic-fuzzer"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Fuzzer for fixed point arithmetic primitives."
documentation = "https://docs.rs/sp-arithmetic-fuzzer"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
honggfuzz = { version = "0.5.49", registry = "local" }
num-bigint = { version = "0.4.3", registry = "local" }
primitive-types = { version = "0.12.0", registry = "local" }
sp-arithmetic = { version = "7.0.0", path = ".." , registry = "local" }

[[bin]]
name = "biguint"
path = "src/biguint.rs"

[[bin]]
name = "normalize"
path = "src/normalize.rs"

[[bin]]
name = "per_thing_rational"
path = "src/per_thing_rational.rs"

[[bin]]
name = "multiply_by_rational_with_rounding"
path = "src/multiply_by_rational_with_rounding.rs"

[[bin]]
name = "fixed_point"
path = "src/fixed_point.rs"
