[package]
name = "sc-runtime-test"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
publish = false
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
paste = { version = "1.0.6", registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../../../primitives/core" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, features = ["improved_panic_error_reporting"], path = "../../../primitives/io" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../../primitives/runtime" , registry = "local" }
sp-sandbox = { version = "0.10.0", default-features = false, path = "../../../primitives/sandbox" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../../primitives/std" , registry = "local" }
sp-tasks = { version = "4.0.0-dev", default-features = false, path = "../../../primitives/tasks" , registry = "local" }

[build-dependencies]
substrate-wasm-builder = { version = "6.0.0", path = "../../../utils/wasm-builder" , registry = "local" }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-sandbox/std",
	"sp-std/std",
	"sp-tasks/std",
]
