[package]
name = "beefy-gadget-rpc"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository = "https://github.com/paritytech/substrate"
description = "RPC for the BEEFY Client gadget for substrate"
homepage = "https://substrate.io"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
jsonrpsee = { version = "0.15.1", features = ["server", "macros"] , registry = "local" }
log = { version = "0.4", registry = "local" }
parking_lot = { version = "0.12.1", registry = "local" }
serde = { version = "1.0.136", features = ["derive"] , registry = "local" }
thiserror = { version = "1.0", registry = "local" }
beefy-gadget = { version = "4.0.0-dev", path = "../." , registry = "local" }
beefy-primitives = { version = "4.0.0-dev", path = "../../../primitives/beefy" , registry = "local" }
sc-rpc = { version = "4.0.0-dev", path = "../../rpc" , registry = "local" }
sc-utils = { version = "10.0.0", path = "../../utils" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }

[dev-dependencies]
serde_json = { version = "1.0.85", registry = "local" }
sc-rpc = { version = "4.0.0-dev", features = [
	"test-helpers",
], path = "../../rpc" , registry = "local" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" , registry = "local" }
tokio = { version = "1.17.0", features = ["macros"] , registry = "local" }
