[package]
name = "sc-executor-wasmi"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "This crate provides an implementation of `WasmRuntime` that is baked by wasmi."
documentation = "https://docs.rs/sc-executor-wasmi"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" , registry = "local" }
log = { version = "0.4.17", registry = "local" }
wasmi = { version = "0.13", registry = "local" }
sc-allocator = { version = "4.1.0-dev", path = "../../allocator" , registry = "local" }
sc-executor-common = { version = "0.10.0-dev", path = "../common" , registry = "local" }
sp-runtime-interface = { version = "6.0.0", path = "../../../primitives/runtime-interface" , registry = "local" }
sp-sandbox = { version = "0.10.0-dev", path = "../../../primitives/sandbox" , registry = "local" }
sp-wasm-interface = { version = "7.0.0", path = "../../../primitives/wasm-interface" , registry = "local" }
