[package]
name = "node-testing"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test utilities for Substrate node."
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" , registry = "local" }
fs_extra = { version = "1", registry = "local" }
futures = { version = "0.3.21", registry = "local" }
log = { version = "0.4.17", registry = "local" }
tempfile = { version = "3.1.0", registry = "local" }
frame-system = { version = "4.0.0-dev", path = "../../../frame/system" , registry = "local" }
node-executor = { version = "3.0.0-dev", path = "../executor" , registry = "local" }
node-primitives = { version = "2.0.0", path = "../primitives" , registry = "local" }
kitchensink-runtime = { version = "3.0.0-dev", path = "../runtime" , registry = "local" }
pallet-asset-tx-payment = { version = "4.0.0-dev", path = "../../../frame/transaction-payment/asset-tx-payment" , registry = "local" }
pallet-transaction-payment = { version = "4.0.0-dev", path = "../../../frame/transaction-payment" , registry = "local" }
sc-block-builder = { version = "0.10.0-dev", path = "../../../client/block-builder" , registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../../client/api" , registry = "local" }
sc-client-db = { version = "0.10.0-dev", features = ["rocksdb"], path = "../../../client/db" , registry = "local" }
sc-consensus = { version = "0.10.0-dev", path = "../../../client/consensus/common" , registry = "local" }
sc-executor = { version = "0.10.0-dev", features = [
	"wasmtime",
], path = "../../../client/executor" , registry = "local" }
sc-service = { version = "0.10.0-dev", features = [
	"test-helpers",
	"rocksdb",
], path = "../../../client/service" , registry = "local" }
sp-api = { version = "4.0.0-dev", path = "../../../primitives/api" , registry = "local" }
sp-block-builder = { version = "4.0.0-dev", path = "../../../primitives/block-builder" , registry = "local" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" , registry = "local" }
sp-consensus = { version = "0.10.0-dev", path = "../../../primitives/consensus/common" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-inherents = { version = "4.0.0-dev", path = "../../../primitives/inherents" , registry = "local" }
sp-io = { version = "6.0.0", path = "../../../primitives/io" , registry = "local" }
sp-keyring = { version = "6.0.0", path = "../../../primitives/keyring" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }
sp-timestamp = { version = "4.0.0-dev", default-features = false, path = "../../../primitives/timestamp" , registry = "local" }
substrate-test-client = { version = "2.0.0", path = "../../../test-utils/client" , registry = "local" }
