[package]
name = "sp-api-proc-macro"
version = "9.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Macros for declaring and implementing runtime apis."
documentation = "https://docs.rs/sp-api-proc-macro"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
quote = { version = "1.0.10", registry = "local" }
syn = { version = "1.0.98", features = ["full", "fold", "extra-traits", "visit"] , registry = "local" }
proc-macro2 = { version = "1.0.37", registry = "local" }
blake2 = { version = "0.10.4", default-features = false , registry = "local" }
proc-macro-crate = { version = "1.1.3", registry = "local" }

# Required for the doc tests
[features]
default = [ "std" ]
std = []
