[package]
name = "pallet-preimage"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet for storing preimages of hashes"
readme = "README.md"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, path = "../benchmarking" , registry = "local" }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" , registry = "local" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, optional = true, path = "../../primitives/core" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../../primitives/io" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../primitives/runtime" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../primitives/std" , registry = "local" }
log = { version = "0.4.17", default-features = false , registry = "local" }

[dev-dependencies]
pallet-balances = { version = "4.0.0-dev", path = "../balances" , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../../primitives/core" , registry = "local" }

[features]
default = ["std"]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = [
	"frame-support/try-runtime",
]
