[package]
name = "node-inspect"
version = "0.9.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node block inspection tool."
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { version = "4.0.9", features = ["derive"] , registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0" , registry = "local" }
thiserror = { version = "1.0", registry = "local" }
sc-cli = { version = "0.10.0-dev", path = "../../../client/cli" , registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../../client/api" , registry = "local" }
sc-executor = { version = "0.10.0-dev", path = "../../../client/executor" , registry = "local" }
sc-service = { version = "0.10.0-dev", default-features = false, path = "../../../client/service" , registry = "local" }
sp-blockchain = { version = "4.0.0", path = "../../../primitives/blockchain" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }
