[package]
name = "sp-state-machine"
version = "0.12.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate State Machine"
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sp-state-machine"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false , registry = "local" }
hash-db = { version = "0.15.2", default-features = false , registry = "local" }
log = { version = "0.4.17", optional = true , registry = "local" }
num-traits = { version = "0.2.8", default-features = false , registry = "local" }
parking_lot = { version = "0.12.1", optional = true , registry = "local" }
rand = { version = "0.7.2", optional = true , registry = "local" }
smallvec = { version = "1.8.0", registry = "local" }
thiserror = { version = "1.0.30", optional = true , registry = "local" }
tracing = { version = "0.1.29", optional = true , registry = "local" }
trie-root = { version = "0.17.0", default-features = false , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../core" , registry = "local" }
sp-externalities = { version = "0.13.0", default-features = false, path = "../externalities" , registry = "local" }
sp-panic-handler = { version = "10.0.0", optional = true, path = "../panic-handler" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }
sp-trie = { version = "6.0.0", default-features = false, path = "../trie" , registry = "local" }

[dev-dependencies]
array-bytes = { version = "4.1", registry = "local" }
pretty_assertions = { version = "1.2.1", registry = "local" }
rand = { version = "0.7.2", registry = "local" }
sp-runtime = { version = "6.0.0", path = "../runtime" , registry = "local" }
trie-db = { version = "0.24.0", registry = "local" }
assert_matches = { version = "1.5", registry = "local" }

[features]
default = ["std"]
std = [
	"codec/std",
	"hash-db/std",
	"log",
	"num-traits/std",
	"parking_lot",
	"rand",
	"sp-core/std",
	"sp-externalities/std",
	"sp-panic-handler",
	"sp-std/std",
	"sp-trie/std",
	"thiserror",
	"tracing",
	"trie-root/std",
]
