[package]
name = "pallet-beefy-mmr"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "BEEFY + MMR runtime utilities"
repository = "https://github.com/paritytech/substrate"
homepage = "https://substrate.io"

[dependencies]
array-bytes = { version = "4.1", optional = true , registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
log = { version = "0.4.17", default-features = false , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
serde = { version = "1.0.136", optional = true , registry = "local" }
beefy-merkle-tree = { version = "4.0.0-dev", default-features = false, path = "./primitives" , registry = "local" }
beefy-primitives = { version = "4.0.0-dev", default-features = false, path = "../../primitives/beefy" , registry = "local" }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" , registry = "local" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" , registry = "local" }
pallet-beefy = { version = "4.0.0-dev", default-features = false, path = "../beefy" , registry = "local" }
pallet-mmr = { version = "4.0.0-dev", default-features = false, path = "../merkle-mountain-range" , registry = "local" }
pallet-session = { version = "4.0.0-dev", default-features = false, path = "../session" , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../../primitives/core" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../../primitives/io" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../primitives/runtime" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../primitives/std" , registry = "local" }

[dev-dependencies]
array-bytes = { version = "4.1", registry = "local" }
sp-staking = { version = "4.0.0-dev", path = "../../primitives/staking" , registry = "local" }

[features]
default = ["std"]
std = [
	"array-bytes",
	"beefy-merkle-tree/std",
	"beefy-primitives/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-beefy/std",
	"pallet-mmr/std",
	"pallet-session/std",
	"scale-info/std",
	"serde",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = ["frame-support/try-runtime"]
