[package]
name = "remote-externalities"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "An externalities provided environment that can load itself from remote nodes or cached files"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" , registry = "local" }
env_logger = { version = "0.9", registry = "local" }
log = { version = "0.4.17", registry = "local" }
serde = { version = "1.0.136", registry = "local" }
serde_json = { version = "1.0", registry = "local" }
frame-support = { version = "4.0.0", optional = true, path = "../../../frame/support" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-io = { version = "6.0.0", path = "../../../primitives/io" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }
sp-version = { version = "5.0.0", path = "../../../primitives/version" , registry = "local" }
substrate-rpc-client = { path = "../rpc/client" , registry = "local" }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] , registry = "local" }
frame-support = { version = "4.0.0", path = "../../../frame/support" , registry = "local" }
pallet-elections-phragmen = { version = "5.0.0-dev", path = "../../../frame/elections-phragmen" , registry = "local" }

[features]
remote-test = ["frame-support"]
