[package]
name = "sp-keyring"
version = "6.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Keyring support code for the runtime. A set of test accounts."
documentation = "https://docs.rs/sp-keyring"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
lazy_static = { version = "1.4.0", registry = "local" }
strum = { version = "0.24.1", features = ["derive"] , registry = "local" }
sp-core = { version = "6.0.0", path = "../core" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../runtime" , registry = "local" }
