[package]
name = "sp-panic-handler"
version = "10.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Custom panic hook with bug report link"
documentation = "https://docs.rs/sp-panic-handler"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
backtrace = { version = "0.3.64", registry = "local" }
lazy_static = { version = "1.4.0", registry = "local" }
regex = { version = "1.6.0", registry = "local" }
