[package]
name = "substrate-frame-rpc-system"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME's system exposed over Substrate RPC"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde_json = { version = "1", registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0" , registry = "local" }
jsonrpsee = { version = "0.15.1", features = ["server"] , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
log = { version = "0.4.17", registry = "local" }
frame-system-rpc-runtime-api = { version = "4.0.0-dev", path = "../../../../frame/system/rpc/runtime-api" , registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../../../client/api" , registry = "local" }
sc-rpc-api = { version = "0.10.0-dev", path = "../../../../client/rpc-api" , registry = "local" }
sc-transaction-pool-api = { version = "4.0.0-dev", path = "../../../../client/transaction-pool/api" , registry = "local" }
sp-api = { version = "4.0.0", path = "../../../../primitives/api" , registry = "local" }
sp-block-builder = { version = "4.0.0-dev", path = "../../../../primitives/block-builder" , registry = "local" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../../primitives/blockchain" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../../primitives/core" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../../primitives/runtime" , registry = "local" }

[dev-dependencies]
sc-transaction-pool = { version = "4.0.0-dev", path = "../../../../client/transaction-pool" , registry = "local" }
tokio = { version = "1.17.0", registry = "local" }
assert_matches = { version = "1.3.0", registry = "local" }
sp-tracing = { version = "6.0.0", path = "../../../../primitives/tracing" , registry = "local" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../../test-utils/runtime/client" , registry = "local" }
