[package]
name = "sp-runtime-interface-test-wasm-deprecated"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
build = "build.rs"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = { version = "6.0.0", default-features = false, path = "../../core" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../../io" , registry = "local" }
sp-runtime-interface = { version = "6.0.0", default-features = false, path = "../" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../std" , registry = "local" }

[build-dependencies]
substrate-wasm-builder = { version = "5.0.0-dev", path = "../../../utils/wasm-builder" , registry = "local" }

[features]
default = [ "std" ]
std = [ "sp-core/std", "sp-io/std", "sp-runtime-interface/std", "sp-std/std" ]
