[package]
name = "substrate-frame-rpc-support"
version = "3.0.0"
authors = [
	"Parity Technologies <admin@parity.io>",
	"Andrew Dirksen <andrew@dirksen.com>",
]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate RPC for FRAME's support"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
jsonrpsee = { version = "0.15.1", features = ["jsonrpsee-types"] , registry = "local" }
serde = { version = "1", registry = "local" }
frame-support = { version = "4.0.0", path = "../../../../frame/support" , registry = "local" }
sc-rpc-api = { version = "0.10.0-dev", path = "../../../../client/rpc-api" , registry = "local" }
sp-storage = { version = "6.0.0", path = "../../../../primitives/storage" , registry = "local" }

[dev-dependencies]
scale-info = { version = "2.1.1", registry = "local" }
jsonrpsee = { version = "0.15.1", features = ["ws-client", "jsonrpsee-types"] , registry = "local" }
tokio = { version = "1.17.0", registry = "local" }
sp-core = { version = "6.0.0", path = "../../../../primitives/core" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../../primitives/runtime" , registry = "local" }
frame-system = { version = "4.0.0", path = "../../../../frame/system" , registry = "local" }
