[package]
name = "frame-election-solution-type-fuzzer"
version = "2.0.0-alpha.5"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Fuzzer for phragmén solution type implementation."
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { version = "4.0.9", features = ["derive"] , registry = "local" }
honggfuzz = { version = "0.5", registry = "local" }
rand = { version = "0.8", features = ["std", "small_rng"] , registry = "local" }

codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
frame-election-provider-solution-type = { version = "7.0.0", path = ".." , registry = "local" }
frame-election-provider-support = { version = "4.0.0-dev", path = "../.." , registry = "local" }
sp-arithmetic = { version = "6.0.0", path = "../../../../primitives/arithmetic" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../../primitives/runtime" , registry = "local" }
# used by generate_solution_type:
sp-npos-elections = { version = "4.0.0-dev", default-features = false, path = "../../../../primitives/npos-elections" , registry = "local" }
frame-support = { version = "4.0.0-dev", path = "../../../support" , registry = "local" }

[[bin]]
name = "compact"
path = "src/compact.rs"
