[package]
name = "chain-spec-builder"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ansi_term = { version = "0.12.1", registry = "local" }
clap = { version = "4.0.9", features = ["derive"] , registry = "local" }
rand = { version = "0.8", registry = "local" }
node-cli = { version = "3.0.0-dev", path = "../../node/cli" , registry = "local" }
sc-chain-spec = { version = "4.0.0-dev", path = "../../../client/chain-spec" , registry = "local" }
sc-keystore = { version = "4.0.0-dev", path = "../../../client/keystore" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-keystore = { version = "0.12.0", path = "../../../primitives/keystore" , registry = "local" }
