[package]
name = "pallet-asset-tx-payment"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "pallet to manage transaction payments in assets"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate dependencies
sp-core = { version = "6.0.0", default-features = false, path = "../../../primitives/core" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../../../primitives/io" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../../primitives/runtime" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../../primitives/std" , registry = "local" }

frame-support = { version = "4.0.0", default-features = false, path = "../../support" , registry = "local" }
frame-system = { version = "4.0.0", default-features = false, path = "../../system" , registry = "local" }
pallet-transaction-payment = { version = "4.0.0-dev", default-features = false, path = ".." , registry = "local" }

# Other dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
serde = { version = "1.0.136", optional = true , registry = "local" }

[dev-dependencies]
serde_json = { version = "1.0.85", registry = "local" }

sp-storage = { version = "6.0.0", default-features = false, path = "../../../primitives/storage" , registry = "local" }

pallet-assets = { version = "4.0.0-dev", path = "../../assets" , registry = "local" }
pallet-authorship = { version = "4.0.0-dev", path = "../../authorship" , registry = "local" }
pallet-balances = { version = "4.0.0-dev", path = "../../balances" , registry = "local" }


[features]
default = ["std"]
std = [
	"scale-info/std",
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"sp-core/std",
	"pallet-transaction-payment/std",
]
try-runtime = ["frame-support/try-runtime"]
