[package]
name = "pallet-staking"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet staking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.136", optional = true , registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
	"derive",
] , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../primitives/std" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../../primitives/io" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../primitives/runtime" , registry = "local" }
sp-staking = { version = "4.0.0-dev", default-features = false, path = "../../primitives/staking" , registry = "local" }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" , registry = "local" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" , registry = "local" }
pallet-session = { version = "4.0.0-dev", default-features = false, features = [
	"historical",
], path = "../session" , registry = "local" }
pallet-authorship = { version = "4.0.0-dev", default-features = false, path = "../authorship" , registry = "local" }
sp-application-crypto = { version = "6.0.0", default-features = false, path = "../../primitives/application-crypto" , registry = "local" }
frame-election-provider-support = { version = "4.0.0-dev", default-features = false, path = "../election-provider-support" , registry = "local" }
log = { version = "0.4.17", default-features = false , registry = "local" }

# Optional imports for benchmarking
frame-benchmarking = { version = "4.0.0-dev", default-features = false, path = "../benchmarking", optional = true , registry = "local" }
rand_chacha = { version = "0.2", default-features = false, optional = true , registry = "local" }

[dev-dependencies]
sp-tracing = { version = "5.0.0", path = "../../primitives/tracing" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../primitives/core" , registry = "local" }
sp-npos-elections = { version = "4.0.0-dev", path = "../../primitives/npos-elections" , registry = "local" }
pallet-balances = { version = "4.0.0-dev", path = "../balances" , registry = "local" }
pallet-timestamp = { version = "4.0.0-dev", path = "../timestamp" , registry = "local" }
pallet-staking-reward-curve = { version = "8.0.0", path = "../staking/reward-curve" , registry = "local" }
pallet-bags-list = { version = "4.0.0-dev", path = "../bags-list" , registry = "local" }
substrate-test-utils = { version = "4.0.0-dev", path = "../../test-utils" , registry = "local" }
frame-benchmarking = { version = "4.0.0-dev", path = "../benchmarking" , registry = "local" }
frame-election-provider-support = { version = "4.0.0-dev", path = "../election-provider-support" , registry = "local" }
rand_chacha = { version = "0.2" , registry = "local" }

[features]
default = ["std"]
std = [
	"frame-benchmarking?/std",
	"serde",
	"codec/std",
	"scale-info/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"pallet-bags-list/std",
	"frame-system/std",
	"pallet-authorship/std",
	"sp-application-crypto/std",
	"log/std",
	"frame-election-provider-support/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"rand_chacha",
	"sp-staking/runtime-benchmarks",
	"pallet-bags-list/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
fuzz = [
	"pallet-bags-list/fuzz",
	"frame-election-provider-support/fuzz",
]
