[package]
name = "substrate-wasm-builder"
version = "5.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Utility for building WASM binaries"
edition = "2021"
readme = "README.md"
repository = "https://github.com/paritytech/substrate/"
license = "Apache-2.0"
homepage = "https://substrate.io"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ansi_term = { version = "0.12.1", registry = "local" }
build-helper = { version = "0.1.1", registry = "local" }
cargo_metadata = { version = "0.14.2", registry = "local" }
strum = { version = "0.24.1", features = ["derive"] , registry = "local" }
tempfile = { version = "3.1.0", registry = "local" }
toml = { version = "0.5.4", registry = "local" }
walkdir = { version = "2.3.2", registry = "local" }
sp-maybe-compressed-blob = { version = "8.0.0", path = "../../primitives/maybe-compressed-blob" , registry = "local" }
filetime = { version = "0.2.16", registry = "local" }
wasm-opt = { version = "0.110", registry = "local" }
