[package]
name = "try-runtime-cli"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Cli command runtime testing and dry-running"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { version = "4.0.9", features = ["derive"] , registry = "local" }
log = { version = "0.4.17", registry = "local" }
parity-scale-codec = { version = "3.0.0", registry = "local" }
serde = { version = "1.0.136", registry = "local" }
zstd = { version = "0.11.2", default-features = false , registry = "local" }
remote-externalities = { version = "0.10.0-dev", path = "../../remote-externalities" , registry = "local" }
sc-chain-spec = { version = "4.0.0-dev", path = "../../../../client/chain-spec" , registry = "local" }
sc-cli = { version = "0.10.0-dev", path = "../../../../client/cli" , registry = "local" }
sc-executor = { version = "0.10.0", path = "../../../../client/executor" , registry = "local" }
sc-service = { version = "0.10.0-dev", default-features = false, path = "../../../../client/service" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../../primitives/core" , registry = "local" }
sp-externalities = { version = "0.12.0", path = "../../../../primitives/externalities" , registry = "local" }
sp-io = { version = "6.0.0", path = "../../../../primitives/io" , registry = "local" }
sp-keystore = { version = "0.12.0", path = "../../../../primitives/keystore" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../../primitives/runtime" , registry = "local" }
sp-state-machine = { version = "0.12.0", path = "../../../../primitives/state-machine" , registry = "local" }
sp-version = { version = "5.0.0", path = "../../../../primitives/version" , registry = "local" }
sp-weights = { version = "4.0.0", path = "../../../../primitives/weights" , registry = "local" }
frame-try-runtime = { optional = true, path = "../../../../frame/try-runtime" , registry = "local" , version = "0.10.0" }
substrate-rpc-client = { path = "../../rpc/client" , registry = "local" }

[dev-dependencies]
tokio = { version = "1.17.0", registry = "local" }

[features]
try-runtime = [
	"frame-try-runtime/try-runtime",
]
