[package]
name = "sp-core-hashing-proc-macro"
version = "5.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "This crate provides procedural macros for calculating static hash."
documentation = "https://docs.rs/sp-core-hashing-proc-macro"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.37", registry = "local" }
quote = { version = "1.0.6", registry = "local" }
syn = { version = "1.0.98", features = ["full", "parsing"] , registry = "local" }
sp-core-hashing = { version = "4.0.0", default-features = false, path = "../" , registry = "local" }
