[package]
name = "sp-runtime-interface"
version = "6.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate runtime interface"
documentation = "https://docs.rs/sp-runtime-interface/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bytes = { version = "1.1.0", default-features = false , registry = "local" }
sp-wasm-interface = { version = "6.0.0", path = "../wasm-interface", default-features = false , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }
sp-tracing = { version = "5.0.0", default-features = false, path = "../tracing" , registry = "local" }
sp-runtime-interface-proc-macro = { version = "9.0.0", path = "proc-macro" , registry = "local" }
sp-externalities = { version = "0.12.0", default-features = false, path = "../externalities" , registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["bytes"] , registry = "local" }
static_assertions = { version = "1.0.0", registry = "local" }
primitive-types = { version = "0.12.0", default-features = false , registry = "local" }
sp-storage = { version = "6.0.0", default-features = false, path = "../storage" , registry = "local" }
impl-trait-for-tuples = { version = "0.2.2", registry = "local" }

[dev-dependencies]
sp-runtime-interface-test-wasm = { version = "2.0.0", path = "test-wasm" , registry = "local" }
sp-state-machine = { version = "0.12.0", path = "../state-machine" , registry = "local" }
sp-core = { version = "6.0.0", path = "../core" , registry = "local" }
sp-io = { version = "6.0.0", path = "../io" , registry = "local" }
rustversion = { version = "1.0.6", registry = "local" }
trybuild = { version = "1.0.60", registry = "local" }

[features]
default = [ "std" ]
std = [
	"sp-storage/std",
	"bytes/std",
	"sp-wasm-interface/std",
	"sp-std/std",
	"sp-tracing/std",
	"codec/std",
	"sp-externalities/std",
	"primitive-types/std",
]

# ATTENTION
#
# Only use when you know what you are doing.
#
# Disables static assertions in `impls.rs` that checks the word size. To prevent any footgun, the
# check is changed into a runtime check.
disable_target_static_assertions = []
