[package]
name = "sp-io"
version = "6.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "I/O for Substrate runtimes"
documentation = "https://docs.rs/sp-io"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
bytes = { version = "1.1.0", default-features = false , registry = "local" }
codec = { package = "parity-scale-codec", version = "3.1.3", default-features = false, features = ["bytes"] , registry = "local" }
hash-db = { version = "0.15.2", default-features = false , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../core" , registry = "local" }
sp-keystore = { version = "0.12.0", default-features = false, optional = true, path = "../keystore" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }
libsecp256k1 = { version = "0.7", optional = true , registry = "local" }
sp-state-machine = { version = "0.12.0", default-features = false, optional = true, path = "../state-machine" , registry = "local" }
sp-wasm-interface = { version = "6.0.0", path = "../wasm-interface", default-features = false , registry = "local" }
sp-runtime-interface = { version = "6.0.0", default-features = false, path = "../runtime-interface" , registry = "local" }
sp-trie = { version = "6.0.0", default-features = false, optional = true, path = "../trie" , registry = "local" }
sp-externalities = { version = "0.12.0", default-features = false, path = "../externalities" , registry = "local" }
sp-tracing = { version = "5.0.0", default-features = false, path = "../tracing" , registry = "local" }
log = { version = "0.4.17", optional = true , registry = "local" }
futures = { version = "0.3.21", features = ["thread-pool"], optional = true , registry = "local" }
parking_lot = { version = "0.12.1", optional = true , registry = "local" }
secp256k1 = { version = "0.24.0", features = ["recovery", "global-context"], optional = true , registry = "local" }
tracing = { version = "0.1.29", default-features = false , registry = "local" }
tracing-core = { version = "0.1.28", default-features = false, registry = "local" }

[features]
default = ["std"]
std = [
	"bytes/std",
	"sp-externalities/std",
	"sp-core/std",
	"sp-keystore",
	"codec/std",
	"sp-std/std",
	"hash-db/std",
	"sp-trie/std",
	"sp-state-machine/std",
	"libsecp256k1",
	"secp256k1",
	"sp-runtime-interface/std",
	"sp-wasm-interface/std",
	"sp-tracing/std",
	"tracing/std",
	"tracing-core/std",
	"log",
	"futures",
	"parking_lot",
]

with-tracing = [
	"sp-tracing/with-tracing"
]

# These two features are used for `no_std` builds for the environments which already provides
# `#[panic_handler]`, `#[alloc_error_handler]` and `#[global_allocator]`.
#
# For the regular wasm runtime builds those are not used.
disable_panic_handler = []
disable_oom = []
disable_allocator = []

# This feature flag controls the runtime's behavior when encountering
# a panic or when it runs out of memory, improving the diagnostics.
#
# When enabled the runtime will marshal the relevant error message
# to the host through the `PanicHandler::abort_on_panic` runtime interface.
# This gives the caller direct programmatic access to the error message.
#
# When disabled the error message will only be printed out in the
# logs, with the caller receving a generic "wasm `unreachable` instruction executed"
# error message.
#
# This has no effect if both `disable_panic_handler` and `disable_oom`
# are enabled.
#
# WARNING: Enabling this feature flag requires the `PanicHandler::abort_on_panic`
#          host function to be supported by the host. Do *not* enable it for your
#          runtime without first upgrading your host client!
improved_panic_error_reporting = []
