[package]
name = "sc-consensus-pow"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "PoW consensus algorithm for substrate"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.57", registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
futures-timer = { version = "3.0.1", registry = "local" }
log = { version = "0.4.17", registry = "local" }
parking_lot = { version = "0.12.1", registry = "local" }
thiserror = { version = "1.0", registry = "local" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.17.0", path = "../../../utils/prometheus" , registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../api" , registry = "local" }
sc-consensus = { version = "0.10.0-dev", path = "../../../client/consensus/common" , registry = "local" }
sp-api = { version = "4.0.0", path = "../../../primitives/api" , registry = "local" }
sp-block-builder = { version = "4.0.0", path = "../../../primitives/block-builder" , registry = "local" }
sp-blockchain = { version = "4.0.0", path = "../../../primitives/blockchain" , registry = "local" }
sp-consensus = { version = "0.10.0", path = "../../../primitives/consensus/common" , registry = "local" }
sp-consensus-pow = { version = "0.10.0", path = "../../../primitives/consensus/pow" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-inherents = { version = "4.0.0", path = "../../../primitives/inherents" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }
