[package]
description = "Substrate light network protocol"
name = "sc-network-light"
version = "0.10.0-dev"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-network-light"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = { version = "0.11", registry = "local" }

[dependencies]
array-bytes = { version = "4.1", registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", features = [
    "derive",
] , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
libp2p = { version = "0.49.0", registry = "local" }
log = { version = "0.4.16", registry = "local" }
prost = { version = "0.11", registry = "local" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" , registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../api" , registry = "local" }
sc-network-common = { version = "0.10.0-dev", path = "../common" , registry = "local" }
sc-peerset = { version = "6.0.0", path = "../../peerset" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }
thiserror = { version = "1.0", registry = "local" }
