[package]
name = "sp-tasks"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Runtime asynchronous, pure computational tasks"
documentation = "https://docs.rs/sp-tasks"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { version = "0.4.17", optional = true , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../core" , registry = "local" }
sp-externalities = { version = "0.12.0", optional = true, path = "../externalities" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../io" , registry = "local" }
sp-runtime-interface = { version = "6.0.0", default-features = false, path = "../runtime-interface" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false , registry = "local" }

[features]
default = ["std"]
std = [
	"log",
	"sp-core/std",
	"sp-externalities",
	"sp-io/std",
	"sp-runtime-interface/std",
	"sp-std/std",
]
