[package]
name = "sp-keystore"
version = "0.12.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Keystore primitives."
documentation = "https://docs.rs/sp-core"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.57", registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
merlin = { version = "2.0", default-features = false , registry = "local" }
parking_lot = { version = "0.12.1", default-features = false , registry = "local" }
schnorrkel = { version = "0.9.1", default-features = false, features = ["preaudit_deprecated", "u64_backend"] , registry = "local" }
serde = { version = "1.0", optional = true , registry = "local" }
thiserror = { version = "1.0", registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../core" , registry = "local" }
sp-externalities = { version = "0.13.0", default-features = false, path = "../externalities" , registry = "local" }

[dev-dependencies]
rand = { version = "0.7.2", registry = "local" }
rand_chacha = { version = "0.2.2", registry = "local" }

[features]
default = ["std"]
std = [
	"codec/std",
	"merlin/std",
	"schnorrkel/std",
	"serde",
	"sp-core/std",
	"sp-externalities/std",
]
