[package]
name = "sp-wasm-interface"
version = "7.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Types and traits for interfacing between the host and the wasm runtime."
documentation = "https://docs.rs/sp-wasm-interface"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
impl-trait-for-tuples = { version = "0.2.2", registry = "local" }
log = { version = "0.4.17", optional = true , registry = "local" }
wasmi = { version = "0.13", optional = true , registry = "local" }
wasmtime = { version = "1.0.0", default-features = false, optional = true , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }

[features]
default = [ "std" ]
std = [ "codec/std", "log", "sp-std/std", "wasmi" ]
