[package]
name = "frame-benchmarking-cli"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "CLI for benchmarking FRAME"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { version = "4.1", registry = "local" }
chrono = { version = "0.4", registry = "local" }
clap = { version = "4.0.9", features = ["derive"] , registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0" , registry = "local" }
comfy-table = { version = "6.0.0", default-features = false , registry = "local" }
handlebars = { version = "4.2.2", registry = "local" }
hash-db = { version = "0.15.2", registry = "local" }
Inflector = { version = "0.11.4", registry = "local" }
itertools = { version = "0.10.3", registry = "local" }
kvdb = { version = "0.12.0", registry = "local" }
lazy_static = { version = "1.4.0", registry = "local" }
linked-hash-map = { version = "0.5.4", registry = "local" }
log = { version = "0.4.17", registry = "local" }
memory-db = { version = "0.30.0", registry = "local" }
rand = { version = "0.8.4", features = ["small_rng"] , registry = "local" }
rand_pcg = { version = "0.3.1", registry = "local" }
serde = { version = "1.0.136", registry = "local" }
serde_json = { version = "1.0.85", registry = "local" }
serde_nanos = { version = "0.1.2", registry = "local" }
tempfile = { version = "3.2.0", registry = "local" }
thiserror = { version = "1.0.30", registry = "local" }
thousands = { version = "0.2.0", registry = "local" }
frame-benchmarking = { version = "4.0.0-dev", path = "../../../frame/benchmarking" , registry = "local" }
frame-support = { version = "4.0.0", path = "../../../frame/support" , registry = "local" }
frame-system = { version = "4.0.0-dev", path = "../../../frame/system" , registry = "local" }
sc-block-builder = { version = "0.10.0-dev", path = "../../../client/block-builder" , registry = "local" }
sc-cli = { version = "0.10.0-dev", default-features = false, path = "../../../client/cli" , registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../../client/api" , registry = "local" }
sc-client-db = { version = "0.10.0-dev", default-features = false, path = "../../../client/db" , registry = "local" }
sc-executor = { version = "0.10.0", path = "../../../client/executor" , registry = "local" }
sc-service = { version = "0.10.0-dev", default-features = false, path = "../../../client/service" , registry = "local" }
sc-sysinfo = { version = "6.0.0", path = "../../../client/sysinfo" , registry = "local" }
sp-api = { version = "4.0.0", path = "../../../primitives/api" , registry = "local" }
sp-blockchain = { version = "4.0.0", path = "../../../primitives/blockchain" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-database = { version = "8.0.0", path = "../../../primitives/database" , registry = "local" }
sp-externalities = { version = "0.12.0", path = "../../../primitives/externalities" , registry = "local" }
sp-inherents = { version = "4.0.0", path = "../../../primitives/inherents" , registry = "local" }
sp-keystore = { version = "0.12.0", path = "../../../primitives/keystore" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }
sp-state-machine = { version = "0.12.0", path = "../../../primitives/state-machine" , registry = "local" }
sp-std = { version = "7.0.0", path = "../../../primitives/std" , registry = "local" }
sp-storage = { version = "6.0.0", path = "../../../primitives/storage" , registry = "local" }
sp-trie = { version = "6.0.0", path = "../../../primitives/trie" , registry = "local" }
gethostname = { version = "0.2.3", registry = "local" }

[features]
default = ["rocksdb"]
runtime-benchmarks = ["sc-client-db/runtime-benchmarks"]
rocksdb = ["sc-cli/rocksdb", "sc-client-db/rocksdb"]
