[package]
name = "frame-benchmarking"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Macro for benchmarking a FRAME runtime."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false , registry = "local" }
linregress = { version = "0.4.4", optional = true , registry = "local" }
log = { version = "0.4.17", default-features = false , registry = "local" }
paste = { version = "1.0", registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
serde = { version = "1.0.136", optional = true , registry = "local" }
frame-support = { version = "4.0.0", default-features = false, path = "../support" , registry = "local" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" , registry = "local" }
sp-api = { version = "4.0.0", default-features = false, path = "../../primitives/api" , registry = "local" }
sp-application-crypto = { version = "6.0.0", default-features = false, path = "../../primitives/application-crypto" , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../../primitives/core" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../../primitives/io" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../primitives/runtime" , registry = "local" }
sp-runtime-interface = { version = "6.0.0", default-features = false, path = "../../primitives/runtime-interface" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../primitives/std" , registry = "local" }
sp-storage = { version = "6.0.0", default-features = false, path = "../../primitives/storage" , registry = "local" }

[dev-dependencies]
array-bytes = { version = "4.1", registry = "local" }
rusty-fork = { version = "0.3.0", default-features = false , registry = "local" }
sp-keystore = { version = "0.12.0", path = "../../primitives/keystore" , registry = "local" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"linregress",
	"log/std",
	"scale-info/std",
	"serde",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime-interface/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-storage/std",
]
runtime-benchmarks = [
	"frame-system/runtime-benchmarks",
]
