[package]
description = "Substrate sync network protocol"
name = "sc-network-sync"
version = "0.10.0-dev"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-network-sync"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = { version = "0.11", registry = "local" }

[dependencies]
array-bytes = { version = "4.1", registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
libp2p = { version = "0.49.0", registry = "local" }
log = { version = "0.4.17", registry = "local" }
lru = { version = "0.8.1", registry = "local" }
mockall = { version = "0.11.2", registry = "local" }
prost = { version = "0.11", registry = "local" }
smallvec = { version = "1.8.0", registry = "local" }
thiserror = { version = "1.0", registry = "local" }
fork-tree = { version = "7.0.0", path = "../../../utils/fork-tree" , registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../api" , registry = "local" }
sc-consensus = { version = "0.10.0-dev", path = "../../consensus/common" , registry = "local" }
sc-network-common = { version = "0.10.0-dev", path = "../common" , registry = "local" }
sc-peerset = { version = "7.0.0", path = "../../peerset" , registry = "local" }
sc-utils = { version = "13.0.0", path = "../../utils" , registry = "local" }
sp-arithmetic = { version = "6.0.0", path = "../../../primitives/arithmetic" , registry = "local" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" , registry = "local" }
sp-consensus = { version = "0.10.0", path = "../../../primitives/consensus/common" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-finality-grandpa = { version = "4.0.0", path = "../../../primitives/finality-grandpa" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }

[dev-dependencies]
async-std = { version = "1.11.0", features = ["attributes"] , registry = "local" }
quickcheck = { version = "1.0.3", default-features = false , registry = "local" }
sc-block-builder = { version = "0.10.0-dev", path = "../../block-builder" , registry = "local" }
sp-test-primitives = { version = "2.0.0", path = "../../../primitives/test-primitives" , registry = "local" }
sp-tracing = { version = "6.0.0", path = "../../../primitives/tracing" , registry = "local" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" , registry = "local" }
