[package]
name = "pallet-referenda"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet for inclusive on-chain decisions"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
assert_matches = { version = "1.5", optional = true , registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.3", default-features = false, features = [
	"derive",
] , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
serde = { version = "1.0.136", features = ["derive"], optional = true , registry = "local" }
sp-arithmetic = { version = "6.0.0", default-features = false, path = "../../primitives/arithmetic" , registry = "local" }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, path = "../benchmarking" , registry = "local" }
frame-support = { version = "4.0.0", default-features = false, path = "../support" , registry = "local" }
frame-system = { version = "4.0.0", default-features = false, path = "../system" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../../primitives/io" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../primitives/runtime" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../primitives/std" , registry = "local" }

[dev-dependencies]
assert_matches = { version = "1.5" , registry = "local" }
pallet-balances = { version = "4.0.0-dev", path = "../balances" , registry = "local" }
pallet-preimage = { version = "4.0.0-dev", path = "../preimage" , registry = "local" }
pallet-scheduler = { version = "4.0.0-dev", path = "../scheduler" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../primitives/core" , registry = "local" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-arithmetic/std",
	"frame-system/std",
	"scale-info/std",
	"serde",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"assert_matches",
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
