[package]
name = "sp-consensus-slots"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for slots-based consensus"
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] , registry = "local" }
scale-info = { version = "2.0.0", default-features = false, features = ["derive"] , registry = "local" }
serde = { version = "1.0", features = ["derive"], optional = true , registry = "local" }
sp-arithmetic = { version = "6.0.0", default-features = false, path = "../../arithmetic" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../runtime" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../std" , registry = "local" }
sp-timestamp = { version = "4.0.0", default-features = false, path = "../../timestamp" , registry = "local" }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"serde",
	"sp-arithmetic/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-timestamp/std",
]
