[package]
name = "sp-authorship"
version = "4.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Authorship primitives"
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.57", optional = true , registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
sp-inherents = { version = "4.0.0", default-features = false, path = "../inherents" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../runtime" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }

[features]
default = [ "std" ]
std = [
	"async-trait",
	"codec/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-std/std",
]
