[package]
name = "sp-mmr-primitives"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Merkle Mountain Range primitives."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
log = { version = "0.4.17", default-features = false , registry = "local" }
serde = { version = "1.0.136", features = ["derive"], optional = true , registry = "local" }
sp-api = { version = "4.0.0", default-features = false, path = "../api" , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../core" , registry = "local" }
sp-debug-derive = { version = "9.0.0", default-features = false, path = "../debug-derive" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../runtime" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }

[dev-dependencies]
array-bytes = { version = "4.1", registry = "local" }

[features]
default = ["std"]
std = [
	"codec/std",
	"log/std",
	"serde",
	"sp-api/std",
	"sp-core/std",
	"sp-debug-derive/std",
	"sp-runtime/std",
	"sp-std/std",
]
