[package]
name = "substrate-test-client"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { version = "4.1", registry = "local" }
async-trait = { version = "0.1.57", registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0" , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
serde = { version = "1.0.136", registry = "local" }
serde_json = { version = "1.0.85", registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../client/api" , registry = "local" }
sc-client-db = { version = "0.10.0-dev", default-features = false, features = [
	"test-helpers",
], path = "../../client/db" , registry = "local" }
sc-consensus = { version = "0.10.0-dev", path = "../../client/consensus/common" , registry = "local" }
sc-executor = { version = "0.10.0-dev", path = "../../client/executor" , registry = "local" }
sc-offchain = { version = "4.0.0-dev", path = "../../client/offchain" , registry = "local" }
sc-service = { version = "0.10.0-dev", default-features = false, features = [
	"test-helpers",
], path = "../../client/service" , registry = "local" }
sp-blockchain = { version = "4.0.0-dev", path = "../../primitives/blockchain" , registry = "local" }
sp-consensus = { version = "0.10.0", path = "../../primitives/consensus/common" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../primitives/core" , registry = "local" }
sp-keyring = { version = "6.0.0", path = "../../primitives/keyring" , registry = "local" }
sp-keystore = { version = "0.12.0", path = "../../primitives/keystore" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../primitives/runtime" , registry = "local" }
sp-state-machine = { version = "0.12.0", path = "../../primitives/state-machine" , registry = "local" }
