[package]
name = "frame-support"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Support code for the runtime."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.136", optional = true, features = ["derive"] , registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
frame-metadata = { version = "15.0.0", default-features = false, features = ["v14"] , registry = "local" }
sp-api = { version = "4.0.0-dev", default-features = false, path = "../../primitives/api" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../primitives/std" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../../primitives/io" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../primitives/runtime" , registry = "local" }
sp-tracing = { version = "6.0.0", default-features = false, path = "../../primitives/tracing" , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../../primitives/core" , registry = "local" }
sp-arithmetic = { version = "6.0.0", default-features = false, path = "../../primitives/arithmetic" , registry = "local" }
sp-inherents = { version = "4.0.0-dev", default-features = false, path = "../../primitives/inherents" , registry = "local" }
sp-staking = { version = "4.0.0-dev", default-features = false, path = "../../primitives/staking" , registry = "local" }
sp-weights = { version = "4.0.0", default-features = false, path = "../../primitives/weights" , registry = "local" }
tt-call = { version = "1.0.8", registry = "local" }
frame-support-procedural = { version = "4.0.0-dev", default-features = false, path = "./procedural" , registry = "local" }
paste = { version = "1.0", registry = "local" }
once_cell = { version = "1", default-features = false, optional = true , registry = "local" }
sp-state-machine = { version = "0.12.0", default-features = false, optional = true, path = "../../primitives/state-machine" , registry = "local" }
bitflags = { version = "1.3", registry = "local" }
impl-trait-for-tuples = { version = "0.2.2", registry = "local" }
smallvec = { version = "1.8.0", registry = "local" }
log = { version = "0.4.17", default-features = false , registry = "local" }
sp-core-hashing-proc-macro = { version = "5.0.0", path = "../../primitives/core/hashing/proc-macro" , registry = "local" }
k256 = { version = "0.11.5", default-features = false, features = ["ecdsa"] , registry = "local" }

[dev-dependencies]
serde_json = { version = "1.0.85", registry = "local" }
assert_matches = { version = "1.3.0", registry = "local" }
pretty_assertions = { version = "1.2.1", registry = "local" }
frame-system = { version = "4.0.0-dev", path = "../system" , registry = "local" }
parity-util-mem = { version = "0.12.0", default-features = false, features = ["primitive-types"] , registry = "local" }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"k256/std",
	"once_cell",
	"serde",
	"sp-api/std",
	"sp-io/std",
	"codec/std",
	"scale-info/std",
	"sp-std/std",
	"sp-runtime/std",
	"sp-tracing/std",
	"sp-arithmetic/std",
	"frame-metadata/std",
	"sp-inherents/std",
	"sp-staking/std",
	"sp-state-machine/std",
	"sp-weights/std",
	"frame-support-procedural/std",
	"log/std",
]
runtime-benchmarks = []
try-runtime = []
# By default some types have documentation, `no-metadata-docs` allows to reduce the documentation
# in the metadata.
no-metadata-docs = ["frame-support-procedural/no-metadata-docs"]
# By default some types have documentation, `full-metadata-docs` allows to add documentation to
# more types in the metadata.
full-metadata-docs = ["scale-info/docs"]
# Generate impl-trait for tuples with the given number of tuples. Will be needed as the number of
# pallets in a runtime grows. Does increase the compile time!
tuples-96 = []
tuples-128 = []
