[package]
description = "Endpoint to expose Prometheus metrics"
name = "substrate-prometheus-endpoint"
version = "0.17.0"
license = "Apache-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures-util = { version = "0.3.19", default-features = false, features = ["io"] , registry = "local" }
hyper = { version = "0.14.16", default-features = false, features = ["http1", "server", "tcp"] , registry = "local" }
log = { version = "0.4.17", registry = "local" }
prometheus = { version = "0.13.0", default-features = false , registry = "local" }
thiserror = { version = "1.0", registry = "local" }
tokio = { version = "1.17.0", features = ["parking_lot"] , registry = "local" }

[dev-dependencies]
hyper = { version = "0.14.16", features = ["client"] , registry = "local" }
tokio = { version = "1.17.0", features = ["rt-multi-thread"] , registry = "local" }
