[package]
name = "sp-runtime"
version = "6.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Runtime Modules shared primitive types."
documentation = "https://docs.rs/sp-runtime"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] , registry = "local" }
either = { version = "1.5", default-features = false , registry = "local" }
hash256-std-hasher = { version = "0.15.2", default-features = false , registry = "local" }
impl-trait-for-tuples = { version = "0.2.2", registry = "local" }
log = { version = "0.4.17", default-features = false , registry = "local" }
parity-util-mem = { version = "0.12.0", default-features = false, features = ["primitive-types"] , registry = "local" }
paste = { version = "1.0", registry = "local" }
rand = { version = "0.7.2", optional = true , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
serde = { version = "1.0.136", features = ["derive"], optional = true , registry = "local" }
sp-application-crypto = { version = "6.0.0", default-features = false, path = "../application-crypto" , registry = "local" }
sp-arithmetic = { version = "6.0.0", default-features = false, path = "../arithmetic" , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../core" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../io" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }
sp-weights = { version = "4.0.0", default-features = false, path = "../weights" , registry = "local" }

[dev-dependencies]
rand = { version = "0.7.2", registry = "local" }
serde_json = { version = "1.0.85", registry = "local" }
zstd = { version = "0.11.2", default-features = false , registry = "local" }
sp-api = { version = "4.0.0-dev", path = "../api" , registry = "local" }
sp-state-machine = { version = "0.12.0", path = "../state-machine" , registry = "local" }
sp-tracing = { version = "5.0.0", path = "../../primitives/tracing" , registry = "local" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../test-utils/runtime/client" , registry = "local" }

[features]
runtime-benchmarks = []
default = ["std"]
std = [
	"codec/std",
	"either/use_std",
	"hash256-std-hasher/std",
	"log/std",
	"parity-util-mem/std",
	"rand",
	"scale-info/std",
	"serde",
	"sp-application-crypto/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-io/std",
	"sp-std/std",
	"sp-weights/std",
]
