[package]
description = "Substrate network common"
name = "sc-network-common"
version = "0.10.0-dev"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-network-sync"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = { version = "0.11", registry = "local" }

[dependencies]
async-trait = { version = "0.1.57", registry = "local" }
bitflags = { version = "1.3.2", registry = "local" }
bytes = { version = "1", registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", features = [
	"derive",
] , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
futures-timer = { version = "3.0.2", registry = "local" }
libp2p = { version = "0.49.0", features = [ "request-response", "kad" ] , registry = "local" }
linked_hash_set = { version = "0.1.3", registry = "local" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.16.0", path = "../../../utils/prometheus" , registry = "local" }
smallvec = { version = "1.8.0", registry = "local" }
sc-consensus = { version = "0.10.0-dev", path = "../../consensus/common" , registry = "local" }
sc-peerset = { version = "5.0.0", path = "../../peerset" , registry = "local" }
serde = { version = "1.0.136", features = ["derive"] , registry = "local" }
sp-consensus = { version = "0.10.0-dev", path = "../../../primitives/consensus/common" , registry = "local" }
sp-finality-grandpa = { version = "4.0.0-dev", path = "../../../primitives/finality-grandpa" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" , registry = "local" }
thiserror = { version = "1.0", registry = "local" }
