[package]
name = "node-rpc"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node rpc methods."
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.15.1", features = ["server"] , registry = "local" }
node-primitives = { version = "2.0.0", path = "../primitives" , registry = "local" }
pallet-mmr-rpc = { version = "3.0.0", path = "../../../frame/merkle-mountain-range/rpc/" , registry = "local" }
pallet-transaction-payment-rpc = { version = "4.0.0-dev", path = "../../../frame/transaction-payment/rpc/" , registry = "local" }
sc-chain-spec = { version = "4.0.0-dev", path = "../../../client/chain-spec" , registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../../client/api" , registry = "local" }
sc-consensus-babe = { version = "0.10.0-dev", path = "../../../client/consensus/babe" , registry = "local" }
sc-consensus-babe-rpc = { version = "0.10.0-dev", path = "../../../client/consensus/babe/rpc" , registry = "local" }
sc-consensus-epochs = { version = "0.10.0-dev", path = "../../../client/consensus/epochs" , registry = "local" }
sc-finality-grandpa = { version = "0.10.0-dev", path = "../../../client/finality-grandpa" , registry = "local" }
sc-finality-grandpa-rpc = { version = "0.10.0-dev", path = "../../../client/finality-grandpa/rpc" , registry = "local" }
sc-rpc = { version = "4.0.0-dev", path = "../../../client/rpc" , registry = "local" }
sc-rpc-api = { version = "0.10.0-dev", path = "../../../client/rpc-api" , registry = "local" }
sc-rpc-spec-v2 = { version = "0.10.0-dev", path = "../../../client/rpc-spec-v2" , registry = "local" }
sc-sync-state-rpc = { version = "0.10.0-dev", path = "../../../client/sync-state-rpc" , registry = "local" }
sc-transaction-pool-api = { version = "4.0.0-dev", path = "../../../client/transaction-pool/api" , registry = "local" }
sp-api = { version = "4.0.0-dev", path = "../../../primitives/api" , registry = "local" }
sp-block-builder = { version = "4.0.0-dev", path = "../../../primitives/block-builder" , registry = "local" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" , registry = "local" }
sp-consensus = { version = "0.10.0-dev", path = "../../../primitives/consensus/common" , registry = "local" }
sp-consensus-babe = { version = "0.10.0-dev", path = "../../../primitives/consensus/babe" , registry = "local" }
sp-keystore = { version = "0.12.0", path = "../../../primitives/keystore" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }
substrate-frame-rpc-system = { version = "4.0.0-dev", path = "../../../utils/frame/rpc/system" , registry = "local" }
substrate-state-trie-migration-rpc = { version = "4.0.0-dev", path = "../../../utils/frame/rpc/state-trie-migration-rpc/" , registry = "local" }
