[package]
name = "sp-timestamp"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate core types and inherents for timestamps."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.57", optional = true , registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
futures-timer = { version = "3.0.2", optional = true , registry = "local" }
log = { version = "0.4.17", optional = true , registry = "local" }
thiserror = { version = "1.0.30", optional = true , registry = "local" }
sp-api = { version = "4.0.0-dev", default-features = false, path = "../api" , registry = "local" }
sp-inherents = { version = "4.0.0-dev", default-features = false, path = "../inherents" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../runtime" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }

[features]
default = [ "std" ]
std = [
	"async-trait",
	"codec/std",
	"futures-timer",
	"log",
	"sp-api/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-std/std",
	"thiserror",
]
