[package]
name = "sc-transaction-pool-api"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Transaction pool client facing API."

[dependencies]
async-trait = { version = "0.1.57", registry = "local" }
futures = { version = "0.3.21", registry = "local" }
log = { version = "0.4.17", registry = "local" }
serde = { version = "1.0.136", features = ["derive"] , registry = "local" }
thiserror = { version = "1.0.30", registry = "local" }
sp-blockchain = { version = "4.0.0", path = "../../../primitives/blockchain" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../../primitives/runtime" , registry = "local" }

[dev-dependencies]
serde_json = { version = "1.0", registry = "local" }
