[package]
name = "pallet-mmr-rpc"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Node-specific RPC methods for interaction with Merkle Mountain Range pallet."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" , registry = "local" }
jsonrpsee = { version = "0.15.1", features = ["server", "macros"] , registry = "local" }
serde = { version = "1.0.136", features = ["derive"] , registry = "local" }
sp-api = { version = "4.0.0", path = "../../../primitives/api" , registry = "local" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-mmr-primitives = { version = "4.0.0", path = "../../../primitives/merkle-mountain-range" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }

[dev-dependencies]
serde_json = { version = "1.0.85", registry = "local" }
