[package]
name = "sp-consensus-aura"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Aura consensus"
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.57", optional = true , registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
sp-api = { version = "4.0.0", default-features = false, path = "../../api" , registry = "local" }
sp-application-crypto = { version = "6.0.0", default-features = false, path = "../../application-crypto" , registry = "local" }
sp-consensus = { version = "0.10.0", optional = true, path = "../common" , registry = "local" }
sp-consensus-slots = { version = "0.10.0", default-features = false, path = "../slots" , registry = "local" }
sp-inherents = { version = "4.0.0", default-features = false, path = "../../inherents" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../runtime" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../std" , registry = "local" }
sp-timestamp = { version = "4.0.0", default-features = false, path = "../../timestamp" , registry = "local" }

[features]
default = ["std"]
std = [
	"async-trait",
	"codec/std",
	"scale-info/std",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-consensus",
	"sp-consensus-slots/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-timestamp/std",
]
