[package]
name = "pallet-grandpa"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet for GRANDPA finality gadget"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
log = { version = "0.4.17", default-features = false , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, path = "../benchmarking" , registry = "local" }
frame-support = { version = "4.0.0", default-features = false, path = "../support" , registry = "local" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" , registry = "local" }
pallet-authorship = { version = "4.0.0-dev", default-features = false, path = "../authorship" , registry = "local" }
pallet-session = { version = "4.0.0-dev", default-features = false, path = "../session" , registry = "local" }
sp-application-crypto = { version = "6.0.0", default-features = false, path = "../../primitives/application-crypto" , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../../primitives/core" , registry = "local" }
sp-finality-grandpa = { version = "4.0.0", default-features = false, path = "../../primitives/finality-grandpa" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../../primitives/io" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../primitives/runtime" , registry = "local" }
sp-session = { version = "4.0.0", default-features = false, path = "../../primitives/session" , registry = "local" }
sp-staking = { version = "4.0.0", default-features = false, path = "../../primitives/staking" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../primitives/std" , registry = "local" }

[dev-dependencies]
grandpa = { package = "finality-grandpa", version = "0.16.0", features = ["derive-codec"] , registry = "local" }
frame-benchmarking = { version = "4.0.0-dev", path = "../benchmarking" , registry = "local" }
frame-election-provider-support = { version = "4.0.0-dev", path = "../election-provider-support" , registry = "local" }
pallet-balances = { version = "4.0.0-dev", path = "../balances" , registry = "local" }
pallet-offences = { version = "4.0.0-dev", path = "../offences" , registry = "local" }
pallet-staking = { version = "4.0.0-dev", path = "../staking" , registry = "local" }
pallet-staking-reward-curve = { version = "8.0.0", path = "../staking/reward-curve" , registry = "local" }
pallet-timestamp = { version = "4.0.0-dev", path = "../timestamp" , registry = "local" }
sp-keyring = { version = "6.0.0", path = "../../primitives/keyring" , registry = "local" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-authorship/std",
	"pallet-session/std",
	"scale-info/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-finality-grandpa/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]
