[package]
name = "pallet-nomination-pools-test-staking"
version = "4.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME nomination pools pallet tests with the staking pallet"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] , registry = "local" }
scale-info = { version = "2.0.1", features = ["derive"] , registry = "local" }

sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }
sp-io = { version = "6.0.0", path = "../../../primitives/io" , registry = "local" }
sp-std = { version = "7.0.0", path = "../../../primitives/std" , registry = "local" }
sp-staking = { version = "4.0.0-dev", path = "../../../primitives/staking" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }

frame-system = { version = "4.0.0-dev", path = "../../system" , registry = "local" }
frame-support = { version = "4.0.0-dev", path = "../../support" , registry = "local" }
frame-election-provider-support = { version = "4.0.0-dev", path = "../../election-provider-support" , registry = "local" }

pallet-timestamp = { version = "4.0.0-dev", path = "../../timestamp" , registry = "local" }
pallet-balances = { version = "4.0.0-dev", path = "../../balances" , registry = "local" }
pallet-staking = { version = "4.0.0-dev", path = "../../staking" , registry = "local" }
pallet-bags-list = { version = "4.0.0-dev", path = "../../bags-list" , registry = "local" }
pallet-staking-reward-curve = { version = "7.0.0", path = "../../staking/reward-curve" , registry = "local" }
pallet-nomination-pools = { version = "1.0.0-dev", path = ".." , registry = "local" }

sp-tracing = { version = "5.0.0", path = "../../../primitives/tracing" , registry = "local" }
log = { version = "0.4.0" , registry = "local" }
