[package]
name = "substrate-test-runtime-client"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
sc-block-builder = { version = "0.10.0-dev", path = "../../../client/block-builder" , registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../../client/api" , registry = "local" }
sc-consensus = { version = "0.10.0-dev", path = "../../../client/consensus/common" , registry = "local" }
sp-api = { version = "4.0.0-dev", path = "../../../primitives/api" , registry = "local" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" , registry = "local" }
sp-consensus = { version = "0.10.0-dev", path = "../../../primitives/consensus/common" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }
substrate-test-client = { version = "2.0.0", path = "../../client" , registry = "local" }
substrate-test-runtime = { version = "2.0.0", path = "../../runtime" , registry = "local" }
