[package]
name = "pallet-beefy"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/paritytech/substrate"
description = "BEEFY FRAME pallet"
homepage = "https://substrate.io"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
serde = { version = "1.0.136", optional = true , registry = "local" }
beefy-primitives = { version = "4.0.0", default-features = false, path = "../../primitives/beefy" , registry = "local" }
frame-support = { version = "4.0.0", default-features = false, path = "../support" , registry = "local" }
frame-system = { version = "4.0.0", default-features = false, path = "../system" , registry = "local" }
pallet-session = { version = "4.0.0-dev", default-features = false, path = "../session" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../primitives/runtime" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../primitives/std" , registry = "local" }

[dev-dependencies]
sp-core = { version = "6.0.0", path = "../../primitives/core" , registry = "local" }
sp-io = { version = "6.0.0", path = "../../primitives/io" , registry = "local" }
sp-staking = { version = "4.0.0", path = "../../primitives/staking" , registry = "local" }

[features]
default = ["std"]
std = [
	"beefy-primitives/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-session/std",
	"scale-info/std",
	"serde",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = ["frame-support/try-runtime"]
