[package]
name = "sp-arithmetic"
version = "7.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Minimal fixed point arithmetic primitives and types for runtime."
documentation = "https://docs.rs/sp-arithmetic"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
	"derive",
	"max-encoded-len",
] , registry = "local" }
integer-sqrt = { version = "0.1.2", registry = "local" }
num-traits = { version = "0.2.8", default-features = false , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
serde = { version = "1.0.136", features = ["derive"], optional = true , registry = "local" }
static_assertions = { version = "1.1.0", registry = "local" }
sp-debug-derive = { version = "10.0.0", default-features = false, path = "../debug-derive" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }

[features]
default = ["std"]
std = [
	"codec/std",
	"num-traits/std",
	"scale-info/std",
	"serde",
	"sp-debug-derive/std",
	"sp-std/std",
]

[[bench]]
name = "bench"
harness = false
