[package]
name = "sp-sandbox"
version = "0.10.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "This crate provides means to instantiate and execute wasm modules."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false , registry = "local" }
log = { version = "0.4", default-features = false , registry = "local" }
wasmi = { version = "0.13", default-features = false , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../core" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../io" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }
sp-wasm-interface = { version = "7.0.0", default-features = false, path = "../wasm-interface" , registry = "local" }

[dev-dependencies]
assert_matches = { version = "1.3.0", registry = "local" }
wat = { version = "1.0", registry = "local" }

[features]
default = ["std"]
std = [
	"codec/std",
	"log/std",
	"sp-core/std",
	"sp-io/std",
	"sp-std/std",
	"sp-wasm-interface/std",
	"wasmi/std",
]
strict = []
wasmer-sandbox = []
