[package]
name = "sp-npos-elections"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "NPoS election algorithm primitives"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
serde = { version = "1.0.136", features = ["derive"], optional = true , registry = "local" }
sp-arithmetic = { version = "6.0.0", default-features = false, path = "../arithmetic" , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../core" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../runtime" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }

[dev-dependencies]
rand = { version = "0.7.3", registry = "local" }
substrate-test-utils = { version = "4.0.0-dev", path = "../../test-utils" , registry = "local" }

[features]
default = ["std"]
bench = []
std = [
	"codec/std",
	"scale-info/std",
	"serde",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
