[package]
name = "pallet-alliance"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://docs.substrate.io/"
repository = "https://github.com/paritytech/substrate/"
description = "The Alliance pallet provides a collective for standard-setting industry collaboration."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { version = "4.1", optional = true , registry = "local" }
sha2 = { version = "0.10.1", default-features = false, optional = true , registry = "local" }
log = { version = "0.4.14", default-features = false , registry = "local" }

codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] , registry = "local" }

sp-std = { version = "7.0.0", default-features = false, path = "../../primitives/std" , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../../primitives/core" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../../primitives/io" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../primitives/runtime" , registry = "local" }

frame-benchmarking = { version = "4.0.0-dev", default-features = false, path = "../benchmarking", optional = true , registry = "local" }
frame-support = { version = "4.0.0", default-features = false, path = "../support" , registry = "local" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" , registry = "local" }

pallet-identity = { version = "4.0.0-dev", path = "../identity", default-features = false , registry = "local" }
pallet-collective = { version = "4.0.0-dev", path = "../collective", default-features = false, optional = true , registry = "local" }

[dev-dependencies]
array-bytes = { version = "4.1", registry = "local" }
sha2 = { version = "0.10.1", registry = "local" }
pallet-balances = { version = "4.0.0-dev", path = "../balances" , registry = "local" }
pallet-collective = { version = "4.0.0-dev", path = "../collective" , registry = "local" }

[features]
default = ["std"]
std = [
	"pallet-collective?/std",
	"frame-benchmarking?/std",
	"log/std",
	"codec/std",
	"scale-info/std",
	"sp-std/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-identity/std",
]
runtime-benchmarks = [
	"array-bytes",
	"sha2",
	"frame-benchmarking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
]
