[package]
name = "sc-consensus-aura"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Aura consensus algorithm for substrate"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.57", registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0" , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
log = { version = "0.4.17", registry = "local" }
thiserror = { version = "1.0", registry = "local" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.17.0", path = "../../../utils/prometheus" , registry = "local" }
sc-block-builder = { version = "0.10.0-dev", path = "../../block-builder" , registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../api" , registry = "local" }
sc-consensus = { version = "0.10.0-dev", path = "../../../client/consensus/common" , registry = "local" }
sc-consensus-slots = { version = "0.10.0-dev", path = "../slots" , registry = "local" }
sc-telemetry = { version = "8.0.0", path = "../../telemetry" , registry = "local" }
sp-api = { version = "4.0.0-dev", path = "../../../primitives/api" , registry = "local" }
sp-application-crypto = { version = "6.0.0", path = "../../../primitives/application-crypto" , registry = "local" }
sp-block-builder = { version = "4.0.0-dev", path = "../../../primitives/block-builder" , registry = "local" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" , registry = "local" }
sp-consensus = { version = "0.10.0-dev", path = "../../../primitives/consensus/common" , registry = "local" }
sp-consensus-aura = { version = "0.10.0-dev", path = "../../../primitives/consensus/aura" , registry = "local" }
sp-consensus-slots = { version = "0.10.0-dev", path = "../../../primitives/consensus/slots" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-inherents = { version = "4.0.0-dev", path = "../../../primitives/inherents" , registry = "local" }
sp-keystore = { version = "0.12.0", path = "../../../primitives/keystore" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }

[dev-dependencies]
parking_lot = { version = "0.12.1", registry = "local" }
tempfile = { version = "3.1.0", registry = "local" }
sc-keystore = { version = "4.0.0-dev", path = "../../keystore" , registry = "local" }
sc-network = { version = "0.10.0-dev", path = "../../network" , registry = "local" }
sc-network-test = { version = "0.8.0", path = "../../network/test" , registry = "local" }
sp-keyring = { version = "6.0.0", path = "../../../primitives/keyring" , registry = "local" }
sp-timestamp = { version = "4.0.0-dev", path = "../../../primitives/timestamp" , registry = "local" }
sp-tracing = { version = "6.0.0", path = "../../../primitives/tracing" , registry = "local" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" , registry = "local" }
