[package]
name = "sp-runtime-interface-proc-macro"
version = "8.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "This crate provides procedural macros for usage within the context of the Substrate runtime interface."
documentation = "https://docs.rs/sp-runtime-interface-proc-macro"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
Inflector = { version = "0.11.4", registry = "local" }
proc-macro-crate = { version = "1.1.3", registry = "local" }
proc-macro2 = { version = "1.0.37", registry = "local" }
quote = { version = "1.0.10", registry = "local" }
syn = { version = "1.0.98", features = ["full", "visit", "fold", "extra-traits"] , registry = "local" }
