[package]
name = "substrate-test-utils-derive"
version = "0.13.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate test utilities macros"

[dependencies]
proc-macro-crate = { version = "1.1.3", registry = "local" }
proc-macro2 = { version = "1.0.37", registry = "local" }
quote = { version = "1.0.10", registry = "local" }
syn = { version = "1.0.98", features = ["full"] , registry = "local" }

[lib]
proc-macro = true
