[package]
name = "sp-blockchain"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate blockchain traits and primitives."
documentation = "https://docs.rs/sp-blockchain"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
log = { version = "0.4.17", registry = "local" }
lru = { version = "0.8.1", registry = "local" }
parking_lot = { version = "0.12.1", registry = "local" }
thiserror = { version = "1.0.30", registry = "local" }
sp-api = { version = "4.0.0-dev", path = "../api" , registry = "local" }
sp-consensus = { version = "0.10.0-dev", path = "../consensus/common" , registry = "local" }
sp-database = { version = "8.0.0", path = "../database" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../runtime" , registry = "local" }
sp-state-machine = { version = "0.12.0", path = "../state-machine" , registry = "local" }
