[package]
name = "substrate-state-trie-migration-rpc"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Node-specific RPC methods for interaction with state trie migration."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false , registry = "local" }
serde = { version = "1", features = ["derive"] , registry = "local" }
log = { version = "0.4.17", default-features = false , registry = "local" }

sp-std = { path = "../../../../primitives/std" , version = "7.0.0", registry = "local" }
sp-io = { path = "../../../../primitives/io" , registry = "local" }
sp-core = { path = "../../../../primitives/core" , registry = "local" }
sp-state-machine = { path = "../../../../primitives/state-machine" , registry = "local" }
sp-trie = { path = "../../../../primitives/trie" , registry = "local" }
trie-db = { version = "0.24.0", registry = "local" }

jsonrpsee = { version = "0.15.1", features = ["server", "macros"] , registry = "local" }

# Substrate Dependencies
sc-client-api = { version = "4.0.0-dev", path = "../../../../client/api" , registry = "local" }
sc-rpc-api = { version = "0.10.0-dev", path = "../../../../client/rpc-api" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../../primitives/runtime" , registry = "local" }

[dev-dependencies]
serde_json = { version = "1", registry = "local" }
