[package]
name = "pallet-contracts"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet for WASM contracts"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bitflags = { version = "1.3", registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
	"derive",
	"max-encoded-len",
] , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
log = { version = "0.4", default-features = false , registry = "local" }
wasm-instrument = { version = "0.3", default-features = false , registry = "local" }
serde = { version = "1", optional = true, features = ["derive"] , registry = "local" }
smallvec = { version = "1", default-features = false, features = [
	"const_generics",
] , registry = "local" }
wasmi-validation = { version = "0.5", default-features = false , registry = "local" }
impl-trait-for-tuples = { version = "0.2", registry = "local" }

# Only used in benchmarking to generate random contract code
rand = { version = "0.8", optional = true, default-features = false , registry = "local" }
rand_pcg = { version = "0.3", optional = true , registry = "local" }

# Substrate Dependencies
frame-benchmarking = { version = "4.0.0-dev", default-features = false, path = "../benchmarking", optional = true , registry = "local" }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" , registry = "local" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" , registry = "local" }
pallet-contracts-primitives = { version = "6.0.0", default-features = false, path = "primitives" , registry = "local" }
pallet-contracts-proc-macro = { version = "8.0.0", path = "proc-macro" , registry = "local" }
sp-api = { version = "4.0.0", default-features = false, path = "../../primitives/api" , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../../primitives/core" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../../primitives/io" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../primitives/runtime" , registry = "local" }
sp-sandbox = { version = "0.10.0", default-features = false, path = "../../primitives/sandbox" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../primitives/std" , registry = "local" }

[dev-dependencies]
array-bytes = { version = "4.1", registry = "local" }
assert_matches = { version = "1", registry = "local" }
env_logger = { version = "0.9", registry = "local" }
pretty_assertions = { version = "1", registry = "local" }
wat = { version = "1", registry = "local" }

# Substrate Dependencies
pallet-balances = { version = "4.0.0-dev", path = "../balances" , registry = "local" }
pallet-timestamp = { version = "4.0.0-dev", path = "../timestamp" , registry = "local" }
pallet-randomness-collective-flip = { version = "4.0.0-dev", path = "../randomness-collective-flip" , registry = "local" }
pallet-utility = { version = "4.0.0-dev", path = "../utility" , registry = "local" }
sp-keystore = { version = "0.12.0", path = "../../primitives/keystore" , registry = "local" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"sp-sandbox/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"wasm-instrument/std",
	"wasmi-validation/std",
	"pallet-contracts-primitives/std",
	"pallet-contracts-proc-macro/full",
	"log/std",
	"rand/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"rand",
	"rand_pcg",
	"unstable-interface",
]
try-runtime = ["frame-support/try-runtime"]
# Make contract callable functions marked as __unstable__ available. Do not enable
# on live chains as those are subject to change.
unstable-interface = []
