[package]
name = "sp-database"
version = "7.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate database trait."
documentation = "https://docs.rs/sp-database"
readme = "README.md"

[dependencies]
kvdb = { version = "0.12.0", registry = "local" }
parking_lot = { version = "0.12.1", registry = "local" }
