[package]
name = "sc-consensus-babe"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "BABE consensus algorithm for substrate"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-consensus-babe"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.57", registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
log = { version = "0.4.17", registry = "local" }
merlin = { version = "2.0", registry = "local" }
num-bigint = { version = "0.4.3", registry = "local" }
num-rational = { version = "0.4.1", registry = "local" }
num-traits = { version = "0.2.8", registry = "local" }
parking_lot = { version = "0.12.1", registry = "local" }
schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated"] , registry = "local" }
serde = { version = "1.0.136", features = ["derive"] , registry = "local" }
thiserror = { version = "1.0", registry = "local" }
fork-tree = { version = "7.0.0", path = "../../../utils/fork-tree" , registry = "local" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.17.0", path = "../../../utils/prometheus" , registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../api" , registry = "local" }
sc-consensus = { version = "0.10.0-dev", path = "../../../client/consensus/common" , registry = "local" }
sc-consensus-epochs = { version = "0.10.0-dev", path = "../epochs" , registry = "local" }
sc-consensus-slots = { version = "0.10.0-dev", path = "../slots" , registry = "local" }
sc-keystore = { version = "4.0.0", path = "../../keystore" , registry = "local" }
sc-telemetry = { version = "8.0.0", path = "../../telemetry" , registry = "local" }
sp-api = { version = "4.0.0", path = "../../../primitives/api" , registry = "local" }
sp-application-crypto = { version = "6.0.0", path = "../../../primitives/application-crypto" , registry = "local" }
sp-block-builder = { version = "4.0.0", path = "../../../primitives/block-builder" , registry = "local" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" , registry = "local" }
sp-consensus = { version = "0.10.0", path = "../../../primitives/consensus/common" , registry = "local" }
sp-consensus-babe = { version = "0.10.0-dev", path = "../../../primitives/consensus/babe" , registry = "local" }
sp-consensus-slots = { version = "0.10.0-dev", path = "../../../primitives/consensus/slots" , registry = "local" }
sp-consensus-vrf = { version = "0.10.0", path = "../../../primitives/consensus/vrf" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-inherents = { version = "4.0.0", path = "../../../primitives/inherents" , registry = "local" }
sp-io = { version = "6.0.0", path = "../../../primitives/io" , registry = "local" }
sp-keystore = { version = "0.12.0", path = "../../../primitives/keystore" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }
sp-version = { version = "5.0.0", path = "../../../primitives/version" , registry = "local" }

[dev-dependencies]
rand_chacha = { version = "0.2.2", registry = "local" }
sc-block-builder = { version = "0.10.0-dev", path = "../../block-builder" , registry = "local" }
sp-keyring = { version = "6.0.0", path = "../../../primitives/keyring" , registry = "local" }
sc-network = { version = "0.10.0-dev", path = "../../network" , registry = "local" }
sc-network-test = { version = "0.8.0", path = "../../network/test" , registry = "local" }
sp-timestamp = { version = "4.0.0", path = "../../../primitives/timestamp" , registry = "local" }
sp-tracing = { version = "6.0.0", path = "../../../primitives/tracing" , registry = "local" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" , registry = "local" }
