[package]
name = "sp-api"
version = "4.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate runtime api primitives"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false , registry = "local" }
sp-api-proc-macro = { version = "8.0.0", path = "proc-macro" , registry = "local" }
sp-core = { version = "6.0.0", default-features = false, path = "../core" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../runtime" , registry = "local" }
sp-version = { version = "5.0.0", default-features = false, path = "../version" , registry = "local" }
sp-state-machine = { version = "0.12.0", default-features = false, optional = true, path = "../state-machine" , registry = "local" }
sp-trie = { version = "6.0.0", default-features = false, optional = true, path = "../trie" , registry = "local" }
hash-db = { version = "0.15.2", optional = true , registry = "local" }
thiserror = { version = "1.0.30", optional = true , registry = "local" }

log = { version = "0.4.17", default-features = false , registry = "local" }

[dev-dependencies]
sp-test-primitives = { version = "2.0.0", path = "../test-primitives" , registry = "local" }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime/std",
	"sp-state-machine/std",
	"sp-trie/std",
	"sp-version/std",
	"hash-db",
	"thiserror",
	"log/std",
]
# Special feature to disable logging completly.
#
# By default `sp-api` initializes the `RuntimeLogger` for each runtime api function. However,
# logging functionality increases the code size. It is recommended to enable this feature when
# building a runtime for registering it on chain.
#
# This sets the max logging level to `off` for `log`.
disable-logging = ["log/max_level_off"]
