[package]
name = "node-executor"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" , registry = "local" }
scale-info = { version = "2.1.1", features = ["derive"] , registry = "local" }
frame-benchmarking = { version = "4.0.0-dev", path = "../../../frame/benchmarking" , registry = "local" }
node-primitives = { version = "2.0.0", path = "../primitives" , registry = "local" }
kitchensink-runtime = { version = "3.0.0-dev", path = "../runtime" , registry = "local" }
sc-executor = { version = "0.10.0-dev", path = "../../../client/executor" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-keystore = { version = "0.12.0", path = "../../../primitives/keystore" , registry = "local" }
sp-state-machine = { version = "0.12.0", path = "../../../primitives/state-machine" , registry = "local" }
sp-tracing = { version = "5.0.0", path = "../../../primitives/tracing" , registry = "local" }
sp-trie = { version = "6.0.0", path = "../../../primitives/trie" , registry = "local" }

[dev-dependencies]
criterion = { version = "0.3.0", registry = "local" }
futures = { version = "0.3.21", registry = "local" }
wat = { version = "1.0", registry = "local" }
frame-support = { version = "4.0.0-dev", path = "../../../frame/support" , registry = "local" }
frame-system = { version = "4.0.0-dev", path = "../../../frame/system" , registry = "local" }
node-testing = { version = "3.0.0-dev", path = "../testing" , registry = "local" }
pallet-balances = { version = "4.0.0-dev", path = "../../../frame/balances" , registry = "local" }
pallet-contracts = { version = "4.0.0-dev", path = "../../../frame/contracts" , registry = "local" }
pallet-im-online = { version = "4.0.0-dev", path = "../../../frame/im-online" , registry = "local" }
pallet-sudo = { version = "4.0.0-dev", path = "../../../frame/sudo" , registry = "local" }
pallet-timestamp = { version = "4.0.0-dev", path = "../../../frame/timestamp" , registry = "local" }
pallet-treasury = { version = "4.0.0-dev", path = "../../../frame/treasury" , registry = "local" }
pallet-transaction-payment = { version = "4.0.0-dev", path = "../../../frame/transaction-payment" , registry = "local" }
sp-application-crypto = { version = "6.0.0", path = "../../../primitives/application-crypto" , registry = "local" }
sp-consensus-babe = { version = "0.10.0-dev", path = "../../../primitives/consensus/babe" , registry = "local" }
sp-externalities = { version = "0.12.0", path = "../../../primitives/externalities" , registry = "local" }
sp-keyring = { version = "6.0.0", path = "../../../primitives/keyring" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }

[features]
wasmtime = ["sc-executor/wasmtime"]
stress-test = []

[[bench]]
name = "bench"
harness = false
