[package]
name = "sp-storage"
version = "7.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Storage related primitives"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sp-storage/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
impl-serde = { version = "0.4.0", optional = true , registry = "local" }
ref-cast = { version = "1.0.0", registry = "local" }
serde = { version = "1.0.136", features = ["derive"], optional = true , registry = "local" }
sp-debug-derive = { version = "10.0.0", default-features = false, path = "../debug-derive" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }

[features]
default = [ "std" ]
std = [ "codec/std", "impl-serde", "serde", "sp-debug-derive/std", "sp-std/std" ]
