[package]
name = "pallet-staking-reward-curve"
version = "7.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Reward Curve for FRAME staking pallet"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = { version = "1.1.3", registry = "local" }
proc-macro2 = { version = "1.0.37", registry = "local" }
quote = { version = "1.0.10", registry = "local" }
syn = { version = "1.0.98", features = ["full", "visit"] , registry = "local" }
