[package]
name = "node-template-release"
version = "9.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0"
homepage = "https://substrate.io"
description = "node-template-release"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { version = "4.0.9", features = ["derive"] , registry = "local" }
flate2 = { version = "1.0", registry = "local" }
fs_extra = { version = "1", registry = "local" }
git2 = { version = "0.8", registry = "local" }
glob = { version = "0.2", registry = "local" }
tar = { version = "0.4", registry = "local" }
tempfile = { version = "3", registry = "local" }
toml = { version = "0.4", registry = "local" }

[workspace]
