[package]
name = "sp-consensus"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Common utilities for building and using consensus engines in substrate."
documentation = "https://docs.rs/sp-consensus/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.57", registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", features = [
	"derive",
] , registry = "local" }
futures = { version = "0.3.21", features = ["thread-pool"] , registry = "local" }
futures-timer = { version = "3.0.1", registry = "local" }
log = { version = "0.4.17", registry = "local" }
thiserror = { version = "1.0.30", registry = "local" }
sp-core = { version = "6.0.0", path = "../../core" , registry = "local" }
sp-inherents = { version = "4.0.0-dev", path = "../../inherents" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../runtime" , registry = "local" }
sp-state-machine = { version = "0.12.0", path = "../../state-machine" , registry = "local" }
sp-std = { version = "7.0.0", path = "../../std" , registry = "local" }
sp-version = { version = "5.0.0", path = "../../version" , registry = "local" }

[dev-dependencies]
futures = { version = "0.3.21", registry = "local" }
sp-test-primitives = { version = "2.0.0", path = "../../test-primitives" , registry = "local" }

[features]
default = []
