[package]
name = "pallet-root-offences"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME root offences pallet"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }

pallet-session = { version = "4.0.0-dev", features = [ "historical" ], path = "../../frame/session", default-features = false , registry = "local" }
pallet-staking = { version = "4.0.0-dev", default-features = false, path = "../../frame/staking" , registry = "local" }
pallet-offences = { version = "4.0.0-dev", default-features = false, path = "../../frame/offences" , registry = "local" }

frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" , registry = "local" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../primitives/runtime" , registry = "local" }
sp-staking = { version = "4.0.0", default-features = false, path = "../../primitives/staking" , registry = "local" }

[dev-dependencies]
pallet-balances = { version = "4.0.0-dev", path = "../balances" , registry = "local" }
pallet-timestamp = { version = "4.0.0-dev", path = "../timestamp" , registry = "local" }
pallet-staking-reward-curve = { version = "8.0.0", path = "../staking/reward-curve" , registry = "local" }

sp-core = { version = "6.0.0", path = "../../primitives/core" , registry = "local" }
sp-io = { version = "6.0.0", default-features = false, path = "../../primitives/io" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../primitives/std" , registry = "local" }

frame-election-provider-support = { version = "4.0.0-dev", path = "../election-provider-support" , registry = "local" }

[features]
runtime-benchmarks = []
try-runtime = ["frame-support/try-runtime"]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
    "frame-system/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-offences/std",
	"scale-info/std",
	"sp-runtime/std",
]
