[package]
description = "Substrate bitswap protocol"
name = "sc-network-bitswap"
version = "0.10.0-dev"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-network-bitswap"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = { version = "0.11", registry = "local" }

[dependencies]
cid = { version = "0.8.6", registry = "local" }
futures = { version = "0.3.21", registry = "local" }
libp2p = { version = "0.49.0", registry = "local" }
log = { version = "0.4.17", registry = "local" }
prost = { version = "0.11", registry = "local" }
thiserror = { version = "1.0", registry = "local" }
unsigned-varint = { version = "0.7.1", features = ["futures", "asynchronous_codec"] , registry = "local" }
void = { version = "1.0.2", registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../api" , registry = "local" }
sc-network-common = { version = "0.10.0-dev", path = "../common" , registry = "local" }
sp-blockchain = { version = "4.0.0", path = "../../../primitives/blockchain" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] , registry = "local" }
sc-block-builder = { version = "0.10.0-dev", path = "../../block-builder" , registry = "local" }
sc-consensus = { version = "0.10.0-dev", path = "../../consensus/common" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-consensus = { version = "0.10.0", path = "../../../primitives/consensus/common" , registry = "local" }
substrate-test-runtime = { version = "2.0.0", path = "../../../test-utils/runtime" , registry = "local" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" , registry = "local" }
