[package]
name = "substrate-frame-cli"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "cli interface for FRAME"
documentation = "https://docs.rs/substrate-frame-cli"
readme = "README.md"

[dependencies]
clap = { version = "4.0.9", features = ["derive"] , registry = "local" }
frame-support = { version = "4.0.0", path = "../../../frame/support" , registry = "local" }
frame-system = { version = "4.0.0", path = "../../../frame/system" , registry = "local" }
sc-cli = { version = "0.10.0-dev", path = "../../../client/cli" , registry = "local" }
sp-core = { version = "6.0.0", path = "../../../primitives/core" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }

[features]
default = []
