[package]
description = "Substrate transaction protocol"
name = "sc-network-transactions"
version = "0.10.0-dev"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-network-transactions"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { version = "4.1", registry = "local" }
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] , registry = "local" }
futures = { version = "0.3.21", registry = "local" }
hex = { version = "0.4.0", registry = "local" }
libp2p = { version = "0.49.0", registry = "local" }
log = { version = "0.4.17", registry = "local" }
pin-project = { version = "1.0.12", registry = "local" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.17.0", path = "../../../utils/prometheus" , registry = "local" }
sc-network-common = { version = "0.10.0-dev", path = "../common" , registry = "local" }
sc-peerset = { version = "6.0.0", path = "../../peerset" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }
sp-consensus = { version = "0.10.0-dev", path = "../../../primitives/consensus/common" , registry = "local" }
