[package]
name = "sp-version"
version = "5.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Version module for the Substrate runtime; Provides a function that returns the runtime version."
documentation = "https://docs.rs/sp-version"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
impl-serde = { version = "0.4.0", optional = true , registry = "local" }
parity-wasm = { version = "0.45", optional = true , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
serde = { version = "1.0.136", features = ["derive"], optional = true , registry = "local" }
thiserror = { version = "1.0.30", optional = true , registry = "local" }
sp-core-hashing-proc-macro = { version = "5.0.0", path = "../core/hashing/proc-macro" , registry = "local" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../runtime" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../std" , registry = "local" }
sp-version-proc-macro = { version = "9.0.0", default-features = false, path = "proc-macro" , registry = "local" }

[features]
default = ["std"]
std = [
	"codec/std",
	"impl-serde",
	"parity-wasm",
	"scale-info/std",
	"serde",
	"sp-runtime/std",
	"sp-std/std",
	"thiserror",
]
