[package]
name = "pallet-bags-list"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet bags list"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# parity
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }

# primitives
sp-runtime = { version = "6.0.0", default-features = false, path = "../../primitives/runtime" , registry = "local" }
sp-std = { version = "7.0.0", default-features = false, path = "../../primitives/std" , registry = "local" }

# FRAME
frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" , registry = "local" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" , registry = "local" }
frame-election-provider-support = { version = "4.0.0-dev", default-features = false, path = "../election-provider-support" , registry = "local" }

# third party
log = { version = "0.4.17", default-features = false , registry = "local" }

# Optional imports for benchmarking
frame-benchmarking = { version = "4.0.0-dev", path = "../benchmarking", optional = true, default-features = false , registry = "local" }
pallet-balances = { version = "4.0.0-dev", path = "../balances", optional = true, default-features = false , registry = "local" }
sp-core = { version = "6.0.0", path = "../../primitives/core", optional = true, default-features = false , registry = "local" }
sp-io = { version = "6.0.0", path = "../../primitives/io", optional = true, default-features = false , registry = "local" }
sp-tracing = { version = "6.0.0", path = "../../primitives/tracing", optional = true, default-features = false , registry = "local" }

[dev-dependencies]
sp-core = { version = "6.0.0", path = "../../primitives/core", registry = "local" }
sp-io = { version = "6.0.0", path = "../../primitives/io", registry = "local" }
sp-tracing = { version = "6.0.0", path = "../../primitives/tracing" , registry = "local" }
pallet-balances = { version = "4.0.0-dev", path = "../balances" , registry = "local" }
frame-election-provider-support = { version = "4.0.0-dev", path = "../election-provider-support" , registry = "local" }
frame-benchmarking = { version = "4.0.0-dev", path = "../benchmarking" , registry = "local" }

[features]
default = ["std"]
std = [
	"sp-tracing?/std",
	"sp-io?/std",
	"sp-core?/std",
	"pallet-balances?/std",
	"frame-benchmarking?/std",
	"scale-info/std",
	"codec/std",
	"sp-runtime/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
	"frame-election-provider-support/std",
	"log/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"sp-core",
	"sp-io",
	"pallet-balances/runtime-benchmarks",
	"sp-tracing",
	"frame-election-provider-support/runtime-benchmarks",
]
fuzz = [
	"sp-core",
	"sp-io",
	"pallet-balances",
	"sp-tracing",
	"frame-election-provider-support/fuzz",
]
try-runtime = [ "frame-support/try-runtime" ]
