[package]
name = "frame-support-procedural"
version = "4.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Proc macro of Support code for the runtime."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
Inflector = { version = "0.11.4", registry = "local" }
cfg-expr = { version = "0.10.3", registry = "local" }
itertools = { version = "0.10.3", registry = "local" }
proc-macro2 = { version = "1.0.37", registry = "local" }
quote = { version = "1.0.10", registry = "local" }
syn = { version = "1.0.98", features = ["full", "extra-traits"] , registry = "local" }
frame-support-procedural-tools = { version = "4.0.0", path = "./tools" , registry = "local" }

[features]
default = ["std"]
std = []
no-metadata-docs = []
