[package]
name = "pallet-state-trie-migration"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet migration of trie"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false , registry = "local" }
log = { version = "0.4.17", default-features = false , registry = "local" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] , registry = "local" }
serde = { version = "1.0.133", optional = true , registry = "local" }
thousands = { version = "0.2.0", optional = true , registry = "local" }
zstd = { version = "0.11.2", default-features = false, optional = true , registry = "local" }
frame-benchmarking = { default-features = false, optional = true, path = "../benchmarking" , registry = "local" }
frame-support = { default-features = false, path = "../support" , registry = "local" }
frame-system = { default-features = false, path = "../system" , registry = "local" }
remote-externalities = { optional = true, path = "../../utils/frame/remote-externalities" , registry = "local" }
sp-core = { default-features = false, path = "../../primitives/core" , registry = "local" }
sp-io = { default-features = false, path = "../../primitives/io" , registry = "local" }
sp-runtime = { default-features = false, path = "../../primitives/runtime" , registry = "local" }
sp-std = { default-features = false, path = "../../primitives/std" , version = "7.0.0", registry = "local" }
substrate-state-trie-migration-rpc = { optional = true, path = "../../utils/frame/rpc/state-trie-migration-rpc" , registry = "local" }

[dev-dependencies]
parking_lot = { version = "0.12.1", registry = "local" }
tokio = { version = "1.17.0", features = ["macros"] , registry = "local" }
pallet-balances = { path = "../balances" , registry = "local" }
sp-tracing = { path = "../../primitives/tracing" , registry = "local" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
remote-test = [ "remote-externalities", "serde", "std", "substrate-state-trie-migration-rpc", "thousands", "zstd" ]
