[package]
name = "generate-bags"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Bag threshold generation script for pallet-bag-list"
readme = "README.md"

[dependencies]
# FRAME
frame-support = { version = "4.0.0-dev", path = "../../../frame/support" , registry = "local" }
frame-election-provider-support = { version = "4.0.0-dev", path = "../../../frame/election-provider-support" , registry = "local" }
frame-system = { version = "4.0.0-dev", path = "../../../frame/system" , registry = "local" }
pallet-staking = { version = "4.0.0-dev", path = "../../../frame/staking" , registry = "local" }

# primitives
sp-io = { version = "6.0.0", path = "../../../primitives/io" , registry = "local" }

# third party
chrono = { version = "0.4.19" , registry = "local" }
git2 = { version = "0.14.2", default-features = false , registry = "local" }
num-format = { version = "0.4.3", registry = "local" }
