[package]
name = "substrate-rpc-client"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Shared JSON-RPC client"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.15.1", features = ["ws-client"] , registry = "local" }
sc-rpc-api = { version = "0.10.0-dev", path = "../../../../client/rpc-api" , registry = "local" }
async-trait = { version = "0.1.57", registry = "local" }
serde = { version = "1", registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../../primitives/runtime" , registry = "local" }
log = { version = "0.4", registry = "local" }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "sync"] , registry = "local" }
sp-core = { path = "../../../../primitives/core" , registry = "local" }
