[package]
name = "sc-consensus-epochs"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Generic epochs-based utilities for consensus"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] , registry = "local" }
fork-tree = { version = "7.0.0", path = "../../../utils/fork-tree" , registry = "local" }
sc-client-api = { version = "4.0.0-dev", path = "../../api" , registry = "local" }
sc-consensus = { version = "0.10.0-dev", path = "../common" , registry = "local" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" , registry = "local" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" , registry = "local" }
